### ISSUE TITLE
inconsistent code with paper

### ISSUE THREAD

**Issue by hachi-hachii** [whq-xxh/RSVIS#1]
Seems the code is not consistent with the paper.

In the GRM codes, you seem to just use a linear-transform from dimension (16+4) to dimension (4), but in your paper, layer-specific trainable weight matrix is of shape $C \times C$,  two-type node embeddings is of shape $n_i + 1 \times C$, adjacency matrix is of shape $n_i +1 \times n_i + 1$. Where are these three things and relu in the code? 
Also, what is the usage of `self.lin3`? It seems not used in that module.
Could you please help figured out? Thanks

**Comment by whq-xxh** [comment]
Thank you for your detailed examination of the code and the paper.

In the implementation, linear transformations via layers like lin3 are indeed used to ensure the dimensions align correctly for smooth computations across different tensor operations. This approach helps maintain the integrity of the data structure throughout the network, corresponding to the theoretical model described in the paper.

The concepts of layer-specific trainable weight matrices, node embeddings, and adjacency matrices are integral to the theoretical framework discussed in the paper. In practice, these are implemented and managed through various tensor operations and dimensions within the code. The dimensions used, such as the 256-channel dimension, are consistent with the network’s requirements and serve the purpose of aligning with the C dimension discussed in the paper. As for the nodes, they indeed conform to the n+1 structure, albeit with varying dimensions for each node. This variation is by design to accommodate different types of information processed by the network.

Regarding the use of ReLU, it's a valid point you’ve brought up. In the development of this model, we tested numerous variations, including versions with and without ReLU activations. The results indicated that the performance differences were minimal, hence the version shared might not have included ReLU. However, adding ReLU could potentially benefit specific tasks by introducing non-linearity, and I encourage experimenting with its inclusion to see if it enhances the results for your applications.

We appreciate your feedback and are open to further discussions to refine our approaches. If you have additional insights or suggestions, or if you’re interested in collaborating on this or related projects, please feel free to contact me at [hongqiuwang16@gmail.com]. Welcome to join us.

Thank you for your engagement！

**Comment by whq-xxh** [comment]
I have replied to most of your details in the last reply, you can read it again including lin3, **I noticed your account is anonymous, if you are interested you can make an appointment for a MEETING I'll give you detailed talk, my time is also valuable, don't waste it on endless texts pulling each other apart**, if you're really interested you can make an appointment for a MEETING I respect that you'll be given a further explanation of our paper
