### ISSUE TITLE
code？

### ISSUE THREAD

**Issue by hachi-hachii** [whq-xxh/RSVIS#2]
As the issue#1 mentioned, 
your paper writes "layer-specific trainable weight matrix is of shape $C \times C$",  "two-type node embeddings is of shape $n_i + 1 \times C$", "adjacency matrix is of shape $n_i +1 \times n_i + 1$", **this is how you write originally in the paper**

According to your paper, the three tensor maybe of shape $256\times 256$, $5\times 256$, and $5\times 5$,
where are these threee tensors, **specifically which lines in multimodal_transformer.py**?  For GRM, I can not find anything in the code that accords with your paper. 

**You modified that file after  issue#1 is posted**, seems you want to hide something? Could you help figure out? Thanks in advance!

**Comment by whq-xxh** [comment]
In the implementation, linear transformations via layers like lin3 are indeed used to ensure the dimensions align correctly for smooth computations across different tensor operations. This approach helps maintain the integrity of the data structure throughout the network, corresponding to the theoretical model described in the paper.

The concepts of layer-specific trainable weight matrices, node embeddings, and adjacency matrices are integral to the theoretical framework discussed in the paper. In practice, these are implemented and managed through various tensor operations and dimensions within the code. The dimensions used, such as the 256-channel dimension, are consistent with the network’s requirements and serve the purpose of aligning with the C dimension discussed in the paper. As for the nodes, they indeed conform to the n+1 structure, albeit with varying dimensions for each node. This variation is by design to accommodate different types of information processed by the network.

We appreciate your feedback and are open to further discussions to refine our approaches. If you have additional insights or suggestions, or if you’re interested in collaborating on this or related projects, please feel free to contact me at [hongqiuwang16@gmail.com]. 

**I noticed your account is anonymous, if you are interested you can make an appointment for a MEETING I'll give you detailed talk, my time is also valuable, don't waste it on endless texts pulling each other apart, if you're really interested you can make an appointment for a MEETING I respect that you'll be given a further explanation of our paper**

**Comment by whq-xxh** [comment]
In addition, you can check my records. I didn't hide anything. At the same time, the code of this project is also being sorted out. I think it is reasonable to modify my own github code at any time.

**Comment by whq-xxh** [comment]
The project is being sorted out. **No one has ever said that the code can no longer be modified once it is uploaded. I noticed that you are an anonymous user. Don't worry. If you are really interested, you can email me and make an appointment with me. I will tell you about the paper in detail.**

Sincerely
hongqiu

**Comment by whq-xxh** [comment]
I'll accept your email about a MEETING, but I won't respond if you continue to make **Anonymous and offensive comments!**

**Comment by whq-xxh** [comment]
Thanks. Sorry for any confusion caused by my previous responses. You're welcome to rewrite the code according to your understanding. We have tried several variations ourselves and they should all achieve good results. Going forward, I will pay closer attention to maintaining the code.
